Repository CliMA/ClimaOcean.jl, pull requests merged in 2025-03, with the labels that each got.

#353 Precompute interpolation indices + BarotropicPotentialForcing
  .gitignore
  Project.toml
  examples/single_column_os_papa_simulation.jl
  experiments/one_degree_simulation/Manifest.toml
  experiments/one_degree_simulation/Project.toml
  experiments/one_degree_simulation/debug_tides.jl
  experiments/one_degree_simulation/generate_tidal_forcing.jl
  experiments/one_degree_simulation/one_degree_simulation.jl
  src/ClimaOcean.jl
  src/DataWrangling/ECCO/ECCO_metadata.jl
  src/OceanSeaIceModels/InterfaceComputations/InterfaceComputations.jl
  src/OceanSeaIceModels/InterfaceComputations/assemble_net_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/atmosphere_ocean_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/atmosphere_sea_ice_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl
  src/OceanSeaIceModels/InterfaceComputations/interpolate_atmospheric_state.jl
  src/OceanSeaIceModels/OceanSeaIceModels.jl
  src/OceanSeaIceModels/ocean_sea_ice_model.jl
  src/OceanSeaIceModels/time_step_ocean_sea_ice_model.jl
  src/OceanSimulations/OceanSimulations.jl
  src/OceanSimulations/barotropic_potential_forcing.jl
  src/OceanSimulations/ocean_simulation.jl
  test/runtests_setup.jl
  test/test_ecco.jl
  test/test_jra55.jl
Labels: build docs

#371 Persist FractionalIndices with two separate arrays for `i, j`
  Project.toml
  src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl
  src/OceanSeaIceModels/InterfaceComputations/interpolate_atmospheric_state.jl
  test/test_diagnostics.jl
  test/test_simulations.jl
Labels: tests

#364 Moved ECCO downloading to beginning of code in `examples/one_degree_simulation.jl`
  .gitignore
  examples/one_degree_simulation.jl
  src/DataWrangling/ECCO/ECCO_metadata.jl
Labels: documentation

#391 Add `download_bathymetry`
  src/Bathymetry.jl
Labels: bathymetry ⛰️, user interface

#286 (0.5.1) `Metadata` for JRA55
  .buildkite/pipeline.yml
  .gitignore
  Project.toml
  docs/src/index.md
  examples/ecco_inspect_temperature_salinity.jl
  examples/ecco_mixed_layer_depth.jl
  examples/generate_atmos_dataset.jl
  examples/generate_surface_fluxes.jl
  examples/inspect_JRA55_data.jl
  examples/mediterranean_simulation_with_ecco_restoring.jl
  examples/near_global_ocean_simulation.jl
  examples/one_degree_simulation.jl
  examples/single_column_os_papa_simulation.jl
  src/ClimaOcean.jl
  src/DataWrangling/DataWrangling.jl
  src/DataWrangling/ECCO/ECCO.jl
  src/DataWrangling/ECCO/ECCO_mask.jl
  src/DataWrangling/ECCO/ECCO_metadata.jl
  src/DataWrangling/ECCO/ECCO_restoring.jl
  src/DataWrangling/JRA55.jl
  src/DataWrangling/JRA55/JRA55.jl
  src/DataWrangling/JRA55/JRA55_field_time_series.jl
  src/DataWrangling/JRA55/JRA55_metadata.jl
  src/DataWrangling/JRA55/JRA55_prescribed_atmosphere.jl
  src/DataWrangling/metadata.jl
  src/OceanSeaIceModels/InterfaceComputations/atmosphere_ocean_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl
  src/OceanSeaIceModels/InterfaceComputations/compute_interface_state.jl
  src/OceanSeaIceModels/InterfaceComputations/interface_states.jl
  src/OceanSeaIceModels/InterfaceComputations/similarity_theory_turbulent_fluxes.jl
  src/OceanSeaIceModels/PrescribedAtmospheres.jl
  src/OceanSeaIceModels/ocean_sea_ice_model.jl
  test/runtests.jl
  test/runtests_setup.jl
  test/test_diagnostics.jl
  test/test_distributed_utils.jl
  test/test_downloading.jl
  test/test_ecco.jl
  test/test_jra55.jl
  test/test_surface_fluxes.jl
Labels: build docs

#410 Bugfix: time_step!(model, dt)
  .buildkite/pipeline.yml
  src/OceanSeaIceModels/time_step_ocean_sea_ice_model.jl
  src/OceanSimulations/ocean_simulation.jl
  test/runtests.jl
  test/test_ocean_sea_ice_model.jl
  test/test_ocean_sea_ice_model_parameter_space.jl
Labels: bug

#415 Bugfix in forcing barotropic potential
  src/OceanSimulations/barotropic_potential_forcing.jl
Labels: bug

#411 Fuse kernels for sea_ice_ocean fluxes computation
  src/OceanSeaIceModels/InterfaceComputations/atmosphere_sea_ice_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/sea_ice_ocean_fluxes.jl
Labels: cleanup 🧹

#429 Make README code a bit clearer
  README.md
  docs/src/index.md
Labels: documentation

#438 Add a Reactant Extension
  .buildkite/pipeline.yml
  Project.toml
  ext/ClimaOceanReactantExt.jl
  src/OceanSeaIceModels/InterfaceComputations/atmosphere_ocean_fluxes.jl
  src/OceanSeaIceModels/InterfaceComputations/interface_states.jl
  test/runtests.jl
  test/test_reactant.jl
Labels: extensions 🧬
